name: Ensure German keycodes

on:
  push:
    paths:
      - 'keymap.json'
      - 'default.json'
      - 'custom/layer-overrides.json'
      - 'scripts/translate_to_de.rb'
      - '.github/workflows/translate-de.yml'
  pull_request:
    paths:
      - 'keymap.json'
      - 'default.json'
      - 'custom/layer-overrides.json'
      - 'scripts/translate_to_de.rb'
      - '.github/workflows/translate-de.yml'

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install rake
        run: gem install rake
      - name: Translate keycodes
        run: |
          scripts/translate_to_de.rb
          rake dtsi
      - name: Detect translation drift
        id: diff
        run: |
          if git diff --quiet; then
            echo "clean=true" >> "$GITHUB_OUTPUT"
            echo "No translation drift detected."
          else
            echo "clean=false" >> "$GITHUB_OUTPUT"
            echo "::group::git status"
            git status --short
            echo "::endgroup::"
            echo "::group::git diff --stat"
            git diff --stat
            echo "::endgroup::"
            git diff > translate-de.patch
          fi
      - name: Upload translation patch
        if: steps.diff.outputs.clean == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: translate-de.patch
          path: translate-de.patch
      - name: Fail if translation drift detected
        if: steps.diff.outputs.clean == 'false'
        run: |
          echo "::error::German translation drift detected. Run scripts/translate_to_de.rb and rake dtsi locally, then commit the regenerated files."
          exit 1
